services:
  - type: web
    name: lifebalance-notifications-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DatabaseName
        value: LifeBalanceNotificationsDb
      - key: ConnectionStrings__MongoDb
        sync: false
