<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LifeBalance.Notifications.Application\LifeBalance.Notifications.Application.csproj" />
    <ProjectReference Include="..\LifeBalance.Notifications.Infrastructure\LifeBalance.Notifications.Infrastructure.csproj" />
    <ProjectReference Include="..\LifeBalance.Notifications.Shared\LifeBalance.Notifications.Shared.csproj" />
  </ItemGroup>

</Project>
