<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\LifeBalance.Dashboard.Application\LifeBalance.Dashboard.Application.csproj" />
    <ProjectReference Include="..\LifeBalance.Dashboard.Infrastructure\LifeBalance.Dashboard.Infrastructure.csproj" />
    <ProjectReference Include="..\LifeBalance.Dashboard.Contracts\LifeBalance.Dashboard.Contracts.csproj" />
    <ProjectReference Include="..\LifeBalance.Dashboard.Shared\LifeBalance.Dashboard.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
    <PackageReference Include="AspNetCore.HealthChecks.MongoDb" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.7" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Enrichers.CorrelationId" Version="3.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
