<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LifeBalance.Notifications.Domain\LifeBalance.Notifications.Domain.csproj" />
    <ProjectReference Include="..\LifeBalance.Notifications.Shared\LifeBalance.Notifications.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
