using LifeBalance.Reporting.Domain.Entities;
using LifeBalance.Reporting.Domain.Enums;

namespace LifeBalance.Reporting.Domain.Repositories;

/// <summary>
/// Repository contract for <see cref="ReportGenerationLog"/> persistence.
/// Implemented by the Infrastructure layer using MongoDB.
/// </summary>
public interface IReportGenerationLogRepository
{
    /// <summary>Persists a report generation log entry.</summary>
    /// <param name="log">The log entry to persist.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    Task AddAsync(ReportGenerationLog log, CancellationToken cancellationToken = default);

    /// <summary>Retrieves a paginated history of reports generated by a user.</summary>
    /// <param name="userId">The requesting user identifier.</param>
    /// <param name="pageIndex">Zero based page index.</param>
    /// <param name="pageSize">Page size (clamped 1-100).</param>
    /// <param name="scope">Optional scope filter.</param>
    /// <param name="format">Optional format filter.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    Task<(IReadOnlyList<ReportGenerationLog> Items, int Total)> GetByUserAsync(
        string userId,
        int pageIndex,
        int pageSize,
        ReportScope? scope = null,
        ReportFormat? format = null,
        CancellationToken cancellationToken = default);
}
